apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
spec:
  rules:
  - host: webapp.com
    http:
      paths:
      - path: /get
        pathType: Prefix
        backend:
          service:
            name: sample-app-service
            port:
              number: 80